### ISSUE TITLE
Consider  implementing Default for FPSCounter

### ISSUE THREAD

**Issue by bjadamson** [PistonDevelopers/fps_counter#26]
Hi, I just pulled this into my project. Thanks for making it!

I'm just wondering if you had considered implementing Default for it? It was straightforward to implement inside my project, just thought it might be useful!

```rust
impl Default for FPSCounter {
    fn default() -> Self {
        FPSCounter::new()
    }
}
```

Feel free to close this if your not interested. :)

ninja edit:
 Debug too?

**Comment by bvssvni** [comment]
Yeah, good idea!
